### ISSUE TITLE
would ncem work on sequencing-based spatial transcriptomic data?

### ISSUE THREAD

**Issue by LuyiTian** [theislab/ncem#74]
**Question**

Hi, thank you for developing this great package. I am just wondering have you tried to run it on sequencing-based ST data, and do we need some special set up to make it work?

**Comment by AnnaChristina** [comment]
Hi @LuyiTian,

thank you for your questions. I am not sure I fully understand your question, but let me try to answer. 

In general, we are not limited to specific spatial transcriptomic datasets as we should that ncem can extract valuable cell communication insights across various domains and systems. Strong requirements are having cell wise spatial coordinates, gene expression matrix and annotated cell types. Overall the insights gained with ncem can depend on the tissue measured and the underlying structure. Do you have a dataset in mind that you would like to analyze with ncem?

I hope this answers your question and happy to assist with writing a dataloader!

**Comment by camerongw** [comment]
@AnnaChristina do you think this tool would work with, for example, a sequencing-based technique that _approaches_ single cell resolution but still uses a fixed array like Slide-seqV2? Alternatively, what about deconvoluted Slide-seqV2 spots generated with e.g. RCTD? I have such a dataset and am interested in using this tool

**Comment by AnnaChristina** [comment]
Hi @camerongw, happy to hear you would like to use our method on your dataset. You can use ncem in two ways in this case. 
1. Simply using the Slide-seqV2 data with a particular cluster label which you would like to analyze. 
2. Running a reference based deconvolution on the slide-seqV2 data to extract cell type proportions per spot and respective gene expression vectors inferred by the deconvolution method. 

We used the second approach successfully on visium data that was deconvoluted with cell2location, this [notebook](https://github.com/theislab/ncem_benchmarks/blob/main/notebooks/data_preparation/deconvolution/cell2location_human_lymphnode.ipynb) shows how the output of cell2location should be collected in order to use it with ncem.

We additionally tried DestVi as deconvolution method. If you would like to run ncem on deconvoluted data, it is crucial that the method correctly identifies within-cell-type variation and maps it accordingly as this is the signal ncem picks up. cell2location worked quite well for us. 

I hope this helps and answers your question. Happy to assist with writing a dataloader, so you can test ncem on your data.

**Comment by AnnaChristina** [comment]
closing this issue, but feel free to open it again in case of further questions or issues.
